---
repos:

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --line-length=100

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ".*"
        args: [--profile=black, --project=cdevent]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.1.1
    hooks:
      - id: pydocstyle
        args: [--convention=google]
        exclude: "tests"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 1.1.1
    hooks:
      - id: mypy
        files: "cdevents/.*"
